name: tatari
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  get: ^4.6.6
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.2
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.1
  injectable: ^2.5.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3
  path_provider: ^2.1.4
  crypto: ^3.0.6
  collection: ^1.18.0
  gap: ^3.0.1
  flutter_svg: ^2.0.16
  flutter_easyloading: ^3.0.5
  cupertino_icons: ^1.0.8
  pinput: ^5.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner:
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.4
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/svg/
    - assets/images/png/

  fonts:
    - family: Outfit
      fonts:
       - asset: assets/fonts/Outfit-Light.ttf
         weight: 300
       - asset: assets/fonts/Outfit-Regular.ttf
         weight: 400
       - asset: assets/fonts/Outfit-Medium.ttf
         weight: 500
       - asset: assets/fonts/Outfit-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Outfit-Bold.ttf
         weight: 700
       - asset: assets/fonts/Outfit-ExtraBold.ttf
         weight: 800

flutter_native_splash:
  color: "#6B60A5"
  image: assets/images/ic_splash.png
  android_12:
    image: assets/images/ic_splash.png
    color: "#6B60A5"
