// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3RAADSQxvh1ELS8vs1S_LGhStUDVI27U',
    appId: '1:1021739763941:android:46560c5d6902c770002c0c',
    messagingSenderId: '1021739763941',
    projectId: 'tatari-4d1a6',
    storageBucket: 'tatari-4d1a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn6JU5XvQZKUIa0fxFnMyctFL9wVcNWCQ',
    appId: '1:1021739763941:ios:ada98add6f2b1ce4002c0c',
    messagingSenderId: '1021739763941',
    projectId: 'tatari-4d1a6',
    storageBucket: 'tatari-4d1a6.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC63WCRjejE7XUupH9AFsih3IvfUybQOIY',
    appId: '1:1021739763941:web:1a375fcf87c4da5d002c0c',
    messagingSenderId: '1021739763941',
    projectId: 'tatari-4d1a6',
    authDomain: 'tatari-4d1a6.firebaseapp.com',
    storageBucket: 'tatari-4d1a6.firebasestorage.app',
    measurementId: 'G-2BK479PNR8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn6JU5XvQZKUIa0fxFnMyctFL9wVcNWCQ',
    appId: '1:1021739763941:ios:f422456ed2c191e7002c0c',
    messagingSenderId: '1021739763941',
    projectId: 'tatari-4d1a6',
    storageBucket: 'tatari-4d1a6.firebasestorage.app',
    iosBundleId: 'com.example.tatari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC63WCRjejE7XUupH9AFsih3IvfUybQOIY',
    appId: '1:1021739763941:web:1fbcfe1037c3b1b4002c0c',
    messagingSenderId: '1021739763941',
    projectId: 'tatari-4d1a6',
    authDomain: 'tatari-4d1a6.firebaseapp.com',
    storageBucket: 'tatari-4d1a6.firebasestorage.app',
    measurementId: 'G-MKQET45DH6',
  );

}